version: "2"

services:

    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        env_file:
            - .env
        depends_on:
            - database
            - mailer
        volumes:
            - ./var/documents:/app/var/documents
            - ./var/key_value_store:/app/var/key_value_store
            - ./var/sessions:/app/var/sessions
            - ./var/log:/app/var/log
            # Uncomment following line when in dev
            # - .:/app
        restart: "no"
        networks:
            - db

    database:
        image: mysql:5
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: jeyser
            MYSQL_USER: jeyser
            MYSQL_PASSWORD: jeyser
        volumes:
            - "./docker/mysql:/var/lib/mysql"
        restart: "no"

    mailer:
        build: ./docker/mail
        restart: "no"
        networks:
            - db

networks:
    db:
